---
title: "COVID19 Primary Graphs"
author: "Nathan Haywood"
date: "4/1/2020"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
library(plotly)
library(maps)
library(viridis)
```

```{r}
report_3_31_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-31-2020.csv"))
head(report_3_31_2020)
str(report_3_31_2020)
```

## Total number of cases for each US state.
```{r}
fig1 <- report_3_31_2020 %>% 
  filter (Country_Region == "US") %>%
  group_by(Province_State) %>%
  summarise(Total = sum(Confirmed) + sum(Deaths) + sum(Recovered)) %>%
  ggplot(aes(x = Total,  y = reorder(Province_State, Total))) + 
    geom_point() +
    ggtitle("Total number of Cases for each US State as of 3-31-20") +
    ylab("Country/Region") +
    xlab("Cases")

ggplotly(fig1)
```

## 10 Nation with the Fewest Confirmed Cases
```{r}
fig2 <- report_3_31_2020 %>% 
  group_by(Country_Region) %>%
  summarise(Confirmed = sum(Confirmed)) %>%
  arrange(Confirmed) %>%
  dplyr::slice(1:10) %>%
  ggplot(aes(y = Confirmed,  x = reorder(Country_Region, Confirmed))) + 
    geom_bar(stat = 'identity') +
    ggtitle("10 Nation with Fewest Confirmed Cases as of 3-31-20") +
    ylab("Confirmed Cases") +
    xlab("Country/Region") +
    coord_flip()

ggplotly(fig2)
```

```{r}
US_Time_Series_Confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv"))

US_Time_Series_Confirmed_Long <- US_Time_Series_Confirmed %>% 
               pivot_longer(-c(UID, iso2, iso3, code3, FIPS, Admin2, Province_State, Country_Region, Lat, Long_, Combined_Key),
                            names_to = "Date", values_to = "Confirmed") 

Global_Time_Series_Confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
    dplyr::rename(Province_State = "Province/State", Country_Region = "Country/Region")

Global_Time_Series_Confirmed_Long <- Global_Time_Series_Confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 

US_Time_Series_Deaths <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")) %>%
  select(-Population)

US_Time_Series_Deaths_Long <- US_Time_Series_Deaths %>% 
               pivot_longer(-c(UID, iso2, iso3, code3, FIPS, Admin2, Province_State, Country_Region, Lat, Long_, Combined_Key),
                            names_to = "Date", values_to = "Deaths") 

Global_Time_Series_Deaths <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")) %>%
      dplyr::rename(Province_State = "Province/State", Country_Region = "Country/Region")

Global_Time_Series_Deaths_Long <- Global_Time_Series_Deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 

Global_Time_Series_Recovered <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")) %>%
      dplyr::rename(Province_State = "Province/State", Country_Region = "Country/Region")

Global_Time_Series_Recovered_Long <- Global_Time_Series_Recovered %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Recovered") 
```

```{r}
US_Time_Series_Confirmed_Long <- US_Time_Series_Confirmed_Long %>%
  unite(Key, Combined_Key, Date, sep = ".", remove = FALSE)

US_Time_Series_Deaths_Long <- US_Time_Series_Deaths_Long %>%
    unite(Key, Combined_Key, Date, sep = ".", remove = FALSE)

US_Time_Series_Deaths_Long2 <- US_Time_Series_Deaths_Long %>%
  select(Key, Deaths)

US_Time_Series_Concat <- full_join(US_Time_Series_Confirmed_Long, US_Time_Series_Deaths_Long2, by = c("Key")) %>%
  select(-Key)

US_Time_Series_Concat
```

```{r}
US_Time_Series_Concat$Date <- mdy(US_Time_Series_Concat$Date)

US_Time_Series_Concat
```

```{r}
US_Time_Series_Concat_Counts <- US_Time_Series_Concat %>%
  pivot_longer(-c(UID, iso2, iso3, code3, FIPS, Admin2, Province_State, Country_Region, Lat, Long_, Date, Combined_Key),
               names_to = "Report_Type", values_to = "Counts")

US_Time_Series_Concat_Counts
```

```{r}
Global_Time_Series_Confirmed_Long <- Global_Time_Series_Confirmed_Long %>%
    unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)

Global_Time_Series_Deaths_Long <- Global_Time_Series_Deaths_Long %>%
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)

Global_Time_Series_Recovered_Long <- Global_Time_Series_Recovered_Long %>%
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)

Global_Time_Series_Deaths_Long2 <- Global_Time_Series_Deaths_Long %>%
  select(Key, Deaths)

Global_Time_Series_Recovered_Long2 <- Global_Time_Series_Recovered_Long %>%
  select(Key, Recovered)

Global_Time_Series_Concat_Temp <- full_join(Global_Time_Series_Confirmed_Long, Global_Time_Series_Deaths_Long2, by = c("Key"))

Global_Time_Series_Concat <- full_join(Global_Time_Series_Concat_Temp, Global_Time_Series_Recovered_Long2, by = c("Key")) %>%
  select(-Key)

Global_Time_Series_Concat
```

```{r}
Global_Time_Series_Concat$Date <- mdy(Global_Time_Series_Concat$Date)

Global_Time_Series_Concat
```

```{r}
Global_Time_Series_Concat_Counts <- Global_Time_Series_Concat %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")

Global_Time_Series_Concat_Counts
```

```{r}
fig3 <- US_Time_Series_Concat %>%
  group_by(Province_State, Date) %>%
  summarize_at(c("Confirmed", "Deaths"), sum) %>%
  filter(Province_State %in% c("Connecticut", "Maine", "New Hampshire", "Vermont", "New York", "Rhode Island", "Massachusetts")) %>%
  ggplot(aes(x = Date,  y = Confirmed, color = Province_State)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Cases in the US Northeast")

ggplotly(fig3)
```

```{r}
fig4 <- Global_Time_Series_Concat_Counts %>%
  group_by(Country_Region, Date) %>%
  filter(Country_Region %in% c("Morocco", "Algeria", "Tunisia", "Libya", "Egypt", "Sudan")) %>%
  ggplot(aes(x = Date, y = Counts, color = Report_Type)) +
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Cases in Northern Africa") +
    facet_wrap(~Country_Region, ncol = 2, scales = "free_y")

ggplotly(fig4)
```

```{r}
fig5 <-ggplot(report_3_31_2020 %>%
         filter(Country_Region == "US") %>%
              filter (!Province_State %in% c("Alaska","Hawaii", "American Samoa",
                  "Puerto Rico","Northern Mariana Islands", 
                  "Virgin Islands", "Recovered", "Guam", "Grand Princess",
                  "District of Columbia", "Diamond Princess")) %>%
              filter(Lat > 0) %>%
              arrange(desc(Confirmed)) %>%
              dplyr::slice(1:100), aes(x = Long_, y = Lat, size = Confirmed)) +
    borders("state", colour = "black", fill = "grey") +
    theme_bw() +
    geom_point(shape = 21, color='red', fill='red', alpha = 0.5) +
    labs(title = '100 Regions with the Most US COVID-19 Confirmed cases as of 3-31-20',x = '', y = '',
        size="Cases)") +
    theme(legend.position = "right") +
    coord_fixed(ratio=1.5)

ggplotly(fig5)

```

```{r}
fig6 <- ggplot(subset(Global_Time_Series_Concat, Date %in% seq(min(Date, na.rm = TRUE), max(Date, na.rm = TRUE), 14)), aes(x = Long, y = Lat, size = Confirmed)) +
    borders("world", colour = "black", fill = "grey") +
    theme_bw() +
    geom_point(shape = 21, color='red', fill='red', alpha = 0.5) +
    labs(title = 'Global Growth of the Confirmed Virus Cases',x = 'Longitude', y = 'Latitude',
        size="Cases)") +
    theme(legend.position = "right") +
    coord_fixed(ratio=1.5) +
    facet_wrap(.~Date, ncol = 1)

fig6
```






















